openapi: 3.0.1
info:
  title: Equinix API Authentication Firmware Sets API
  description: 'Equinix APIs use the OAuth 2.0 for authentication and authorization. Equinix supports the resource owner password and the client credentials flow.

    To begin, obtain OAuth 2.0 client credentials from the Equinix Developer Console under "My Apps". Then your client application  requests an access token from the Equinix API Authorization endpoint, extracts the access_token from the response, and sends the Bearer token to the API that you want to access'
  termsOfService: https://www.equinix.com/about/legal/terms
  contact:
    name: Equinix API Support
    url: https://docs.equinix.com/api-support.htm
  version: '1.2'
servers:
- url: https://api.equinix.com
tags:
- description: 'Firmware Sets Management. Notice: Firmware Sets are a test feature currently under active development, and only available to certain users. Please contact Customer Success for more information.

    '
  name: Firmware Sets
paths:
  /organizations/{id}/firmware-sets:
    get:
      description: Returns all firmware sets associated with the organization.
      operationId: getOrganizationFirmwareSets
      parameters:
      - description: Organization UUID
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
      - description: page number to return
        in: query
        name: page
        schema:
          type: integer
      - description: items returned per page.
        in: query
        name: per_page
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirmwareSetListResponse'
          description: Successful operation
        '401':
          description: Error responses are included with 4xx and 5xx HTTP responses from the API service. Either "error" or "errors" will be set.
        '404':
          description: Error responses are included with 4xx and 5xx HTTP responses from the API service. Either "error" or "errors" will be set.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Get Organization's Firmware Sets
      tags:
      - Firmware Sets
  /projects/{id}/firmware-sets:
    get:
      description: Returns all firmware sets associated with the project or organization.
      operationId: getProjectFirmwareSets
      parameters:
      - description: Project UUID
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
      - description: page number to return
        in: query
        name: page
        schema:
          type: integer
      - description: items returned per page.
        in: query
        name: per_page
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirmwareSetListResponse'
          description: Successful operation
        '401':
          description: Error responses are included with 4xx and 5xx HTTP responses from the API service. Either "error" or "errors" will be set.
        '404':
          description: Error responses are included with 4xx and 5xx HTTP responses from the API service. Either "error" or "errors" will be set.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      summary: Get Project's Firmware Sets
      tags:
      - Firmware Sets
components:
  schemas:
    FirmwareSet:
      description: Represents a Firmware Set
      example:
        updated_at: 2000-01-23 04:56:07+00:00
        name: name
        created_at: 2000-01-23 04:56:07+00:00
        attributes:
        - updated_at: 2000-01-23 04:56:07+00:00
          data:
            vendor: vendor
            model: model
            plan: plan
            latest: true
          namespace: namespace
          created_at: 2000-01-23 04:56:07+00:00
        - updated_at: 2000-01-23 04:56:07+00:00
          data:
            vendor: vendor
            model: model
            plan: plan
            latest: true
          namespace: namespace
          created_at: 2000-01-23 04:56:07+00:00
        uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
        component_firmware:
        - component: bmc
          filename: filename
          updated_at: 2000-01-23 04:56:07+00:00
          vendor: equinix
          upstream_url: upstream_url
          checksum: checksum
          created_at: 2000-01-23 04:56:07+00:00
          model:
          - romed8hm3
          - romed8hm3
          repository_url: repository_url
          uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
          version: 1.5.0
        - component: bmc
          filename: filename
          updated_at: 2000-01-23 04:56:07+00:00
          vendor: equinix
          upstream_url: upstream_url
          checksum: checksum
          created_at: 2000-01-23 04:56:07+00:00
          model:
          - romed8hm3
          - romed8hm3
          repository_url: repository_url
          uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
          version: 1.5.0
      properties:
        uuid:
          description: Firmware Set UUID
          example: 0516463a-47ee-4809-9a66-ece8c740eed9
          format: uuid
          readOnly: true
          type: string
        name:
          description: Firmware Set Name
          readOnly: true
          type: string
        created_at:
          description: Datetime when the block was created.
          format: date-time
          readOnly: true
          type: string
        updated_at:
          description: Datetime when the block was updated.
          format: date-time
          readOnly: true
          type: string
        attributes:
          description: Represents a list of attributes
          items:
            $ref: '#/components/schemas/Attribute'
          type: array
        component_firmware:
          description: List of components versions
          items:
            $ref: '#/components/schemas/Component'
          type: array
      required:
      - name
      - uuid
      type: object
    Component:
      example:
        component: bmc
        filename: filename
        updated_at: 2000-01-23 04:56:07+00:00
        vendor: equinix
        upstream_url: upstream_url
        checksum: checksum
        created_at: 2000-01-23 04:56:07+00:00
        model:
        - romed8hm3
        - romed8hm3
        repository_url: repository_url
        uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
        version: 1.5.0
      properties:
        uuid:
          description: Component UUID
          example: 0516463a-47ee-4809-9a66-ece8c740eed9
          format: uuid
          readOnly: true
          type: string
        vendor:
          description: Component vendor
          example: equinix
          readOnly: true
          type: string
        model:
          description: List of models where this component version can be applied
          items:
            example: romed8hm3
            type: string
          readOnly: true
          type: array
        filename:
          description: name of the file
          readOnly: true
          type: string
        version:
          description: Version of the component
          example: 1.5.0
          readOnly: true
          type: string
        component:
          description: Component type
          example: bmc
          readOnly: true
          type: string
        checksum:
          description: File checksum
          readOnly: true
          type: string
        upstream_url:
          description: Location of the file
          readOnly: true
          type: string
        repository_url:
          description: Location of the file in the repository
          readOnly: true
          type: string
        created_at:
          description: Datetime when the block was created.
          format: date-time
          readOnly: true
          type: string
        updated_at:
          description: Datetime when the block was updated.
          format: date-time
          readOnly: true
          type: string
      type: object
    Error:
      description: Error responses are included with 4xx and 5xx HTTP responses from the API service. Either "error" or "errors" will be set.
      properties:
        error:
          description: A description of the error that caused the request to fail.
          type: string
        errors:
          description: A list of errors that contributed to the request failing.
          items:
            description: An error message that contributed to the request failing.
            type: string
          type: array
      type: object
    Attribute:
      example:
        updated_at: 2000-01-23 04:56:07+00:00
        data:
          vendor: vendor
          model: model
          plan: plan
          latest: true
        namespace: namespace
        created_at: 2000-01-23 04:56:07+00:00
      properties:
        namespace:
          description: Attribute namespace
          readOnly: true
          type: string
        created_at:
          description: Datetime when the block was created.
          format: date-time
          readOnly: true
          type: string
        updated_at:
          description: Datetime when the block was updated.
          format: date-time
          readOnly: true
          type: string
        data:
          $ref: '#/components/schemas/AttributeData'
      type: object
    FirmwareSetListResponse:
      description: Represents collection of Firmware Sets
      example:
        total_record_count: 5
        records:
        - updated_at: 2000-01-23 04:56:07+00:00
          name: name
          created_at: 2000-01-23 04:56:07+00:00
          attributes:
          - updated_at: 2000-01-23 04:56:07+00:00
            data:
              vendor: vendor
              model: model
              plan: plan
              latest: true
            namespace: namespace
            created_at: 2000-01-23 04:56:07+00:00
          - updated_at: 2000-01-23 04:56:07+00:00
            data:
              vendor: vendor
              model: model
              plan: plan
              latest: true
            namespace: namespace
            created_at: 2000-01-23 04:56:07+00:00
          uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
          component_firmware:
          - component: bmc
            filename: filename
            updated_at: 2000-01-23 04:56:07+00:00
            vendor: equinix
            upstream_url: upstream_url
            checksum: checksum
            created_at: 2000-01-23 04:56:07+00:00
            model:
            - romed8hm3
            - romed8hm3
            repository_url: repository_url
            uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
            version: 1.5.0
          - component: bmc
            filename: filename
            updated_at: 2000-01-23 04:56:07+00:00
            vendor: equinix
            upstream_url: upstream_url
            checksum: checksum
            created_at: 2000-01-23 04:56:07+00:00
            model:
            - romed8hm3
            - romed8hm3
            repository_url: repository_url
            uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
            version: 1.5.0
        - updated_at: 2000-01-23 04:56:07+00:00
          name: name
          created_at: 2000-01-23 04:56:07+00:00
          attributes:
          - updated_at: 2000-01-23 04:56:07+00:00
            data:
              vendor: vendor
              model: model
              plan: plan
              latest: true
            namespace: namespace
            created_at: 2000-01-23 04:56:07+00:00
          - updated_at: 2000-01-23 04:56:07+00:00
            data:
              vendor: vendor
              model: model
              plan: plan
              latest: true
            namespace: namespace
            created_at: 2000-01-23 04:56:07+00:00
          uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
          component_firmware:
          - component: bmc
            filename: filename
            updated_at: 2000-01-23 04:56:07+00:00
            vendor: equinix
            upstream_url: upstream_url
            checksum: checksum
            created_at: 2000-01-23 04:56:07+00:00
            model:
            - romed8hm3
            - romed8hm3
            repository_url: repository_url
            uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
            version: 1.5.0
          - component: bmc
            filename: filename
            updated_at: 2000-01-23 04:56:07+00:00
            vendor: equinix
            upstream_url: upstream_url
            checksum: checksum
            created_at: 2000-01-23 04:56:07+00:00
            model:
            - romed8hm3
            - romed8hm3
            repository_url: repository_url
            uuid: 0516463a-47ee-4809-9a66-ece8c740eed9
            version: 1.5.0
        page: 6
        total_pages: 5
        page_count: 1
        page_size: 0
      properties:
        page_size:
          description: Max number of items returned in a page
          type: integer
        page:
          description: Page returned
          type: integer
        page_count:
          description: Items returned in current page
          type: integer
        total_pages:
          description: Total count of pages
          type: integer
        total_record_count:
          description: Total count of items
          type: integer
        records:
          description: Represents a list of FirmwareSets
          items:
            $ref: '#/components/schemas/FirmwareSet'
          type: array
      type: object
    AttributeData:
      example:
        vendor: vendor
        model: model
        plan: plan
        latest: true
      properties:
        latest:
          description: Boolean flag to know if the firmware set is the latest for the model and vendor
          readOnly: true
          type: boolean
        model:
          description: Model on which this firmware set can be applied
          readOnly: true
          type: string
        vendor:
          description: Vendor on which this firmware set can be applied
          readOnly: true
          type: string
        plan:
          description: Plan where the firmware set can be applied
          readOnly: true
          type: string
      type: object
x-eqx-api-linter-skip-rules:
- 3
- 38
