openapi: 3.0.1
info:
  title: Equinix API Authentication Prices API
  description: 'Equinix APIs use the OAuth 2.0 for authentication and authorization. Equinix supports the resource owner password and the client credentials flow.

    To begin, obtain OAuth 2.0 client credentials from the Equinix Developer Console under "My Apps". Then your client application  requests an access token from the Equinix API Authorization endpoint, extracts the access_token from the response, and sends the Bearer token to the API that you want to access'
  termsOfService: https://www.equinix.com/about/legal/terms
  contact:
    name: Equinix API Support
    url: https://docs.equinix.com/api-support.htm
  version: '1.2'
servers:
- url: https://api.equinix.com
tags:
- name: Prices
  description: Prices
paths:
  /fabric/v4/prices/search:
    post:
      tags:
      - Prices
      summary: Get Prices
      description: Search prices by search criteria
      operationId: searchPrices
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterBody'
            examples:
              virtualConnectionProductEvplVcTypeFromColoToColo:
                $ref: '#/components/examples/VirtualConnectionProductEvplVcTypeFromColoToColo'
              virtualConnectionProductEvplVcTypeFromColoToColoByPortUuid:
                $ref: '#/components/examples/VirtualConnectionProductEvplVcTypeFromColoToColoByPortUuid'
              virtualConnectionProductEvplVcTypeFromColoToSP:
                $ref: '#/components/examples/VirtualConnectionProductEvplVcTypeFromColoToSP'
              virtualConnectionProductFcrVcTypeFromGWToSP:
                $ref: '#/components/examples/VirtualConnectionProductGwVcTypeFromGWToSP'
              virtualConnectionProductFcrVcTypeFromGWToColo:
                $ref: '#/components/examples/VirtualConnectionProductGwVcTypeFromGWToColo'
              virtualConnectionProductFcrVcTypeFromVDToColo:
                $ref: '#/components/examples/VirtualConnectionProductGwVcTypeFromVDToColo'
              virtualConnectionProductEvplVcTypeFromVDToColo:
                $ref: '#/components/examples/VirtualConnectionProductEvplVcTypeFromVDToColo'
              virtualConnectionProductVdChainTypeFromVDToChaingroup:
                $ref: '#/components/examples/VirtualConnectionProductVdChainTypeFromVDToChaingroup'
              virtualConnectionProductOfflineEvplVcTypeFromColoToSp:
                $ref: '#/components/examples/VirtualConnectionProductOfflineEvplVcTypeFromColoToSp'
              virtualConnectionProductOfflineEvpLanVcTypeFromColoToNetwork:
                $ref: '#/components/examples/VirtualConnectionProductEvpLanVcTypeFromColoToNetwork'
              cloudRouterProduct:
                $ref: '#/components/examples/FabricCloudRouterProduct'
              ipBlockProduct:
                $ref: '#/components/examples/IpBlockProduct'
              virtualPortProduct:
                $ref: '#/components/examples/VirtualPortProduct'
              virtualPortProductUPP:
                $ref: '#/components/examples/VirtualPortProductUPP'
              virtualPortProductIX:
                $ref: '#/components/examples/VirtualPortProductIX'
              precisionTimeProductNtpStandardPackageCode:
                $ref: '#/components/examples/PrecisionTimeNtpStandardPackage'
              precisionTimeProductNtpEnterprisePackageCode:
                $ref: '#/components/examples/PrecisionTimeNtpEnterprisePackage'
              precisionTimeProductPtpStandardPackageCode:
                $ref: '#/components/examples/PrecisionTimePtpStandardPackage'
              precisionTimeProductPtpEnterprisePackageCode:
                $ref: '#/components/examples/PrecisionTimePtpEnterprisePackage'
              metroConnectProduct:
                $ref: '#/components/examples/MetroConnectProduct'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceSearchResponse'
              examples:
                virtualConnection:
                  $ref: '#/components/examples/VirtualConnection'
                ipBlock:
                  $ref: '#/components/examples/IpBlock'
                cloudRouter:
                  $ref: '#/components/examples/FabricCloudRouter'
                virtualPort:
                  $ref: '#/components/examples/VirtualPort'
                virtualPortUPP:
                  $ref: '#/components/examples/VirtualPortUPP'
                virtualPortIX:
                  $ref: '#/components/examples/VirtualPortIX'
                precisionTimeService:
                  $ref: '#/components/examples/PrecisionTimeService'
                metroConnect:
                  $ref: '#/components/examples/MetroConnect'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceErrorList'
              examples:
                example:
                  $ref: '#/components/examples/400_prices'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceErrorList'
              examples:
                example:
                  $ref: '#/components/examples/500_prices'
components:
  examples:
    MetroConnect:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: METRO_CONNECT_PRODUCT
          code: MC00007.PROD
          name: Metro Connect Port Product
          description: Metro Connect Port
          account:
            accountNumber: 200551
          charges:
          - type: MONTHLY_RECURRING
            price: 500
          - type: NON_RECURRING
            price: 0
          currency: USD
          metroConnect:
            type: OPTICAL_MC
            bandwidth: 1000
            pathType: PROTECTED
            connectionDestinationType: COLO
            aSide:
              location:
                ibxCode: CH1
            zSide:
              location:
                ibxCode: CH3
    VirtualConnectionProductVdChainTypeFromVDToChaingroup:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - VD_CHAIN_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - VD
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/bridge/package/code
            operator: '='
            values:
            - REGIONAL
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - CHAINGROUP
    PrecisionTimePtpEnterprisePackage:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - PRECISION_TIME_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '270001'
          - property: /timeService/type
            operator: '='
            values:
            - PTP
          - property: /timeService/package/code
            operator: '='
            values:
            - PTP_ENTERPRISE
          - property: /connection/aSide/accessPoint/location/ibx
            operator: '='
            values:
            - CH3
    VirtualConnectionProductEvplVcTypeFromColoToSP:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - EVPL_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - COLO
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/aSide/accessPoint/port/settings/buyout
            operator: '='
            values:
            - 'false'
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - SP
          - property: /connection/zSide/accessPoint/profile/uuid
            operator: '='
            values:
            - efeed227-765e-4f74-b14c-0c8a739be23e
    VirtualPortProductIX:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_PORT_PRODUCT
          - property: /port/location/ibx
            operator: '='
            values:
            - DA1
          - property: /port/type
            operator: '='
            values:
            - XF_PORT
          - property: /port/bandwidth
            operator: '='
            values:
            - '1000'
          - property: /port/serviceCode
            operator: '='
            values:
            - IX
          - property: /port/connectivitySource/type
            operator: '='
            values:
            - COLO
    VirtualConnection:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: VIRTUAL_CONNECTION_PRODUCT
          code: ECX00015.PROD
          name: Equinix Fabric Virtual Connection Product
          description: Equinix Fabric Virtual Connection
          account:
            accountNumber: 200001
          charges:
          - type: MONTHLY_RECURRING
            price: 500
          currency: USD
          connection:
            type: EVPL_VC
            bandwidth: 100
            aSide:
              accessPoint:
                type: COLO
                location:
                  metroCode: CH
                port:
                  settings:
                    buyout: false
            zSide:
              accessPoint:
                type: SP
                location:
                  metroCode: CH
                profile:
                  uuid: 20d32a80-0d61-4333-bc03-707b591ae2f2
    PrecisionTimeService:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: PRECISION_TIME_PRODUCT
          code: EDG00009.PROD
          name: Equinix Precision Time Product
          description: Equinix Precision Time Product
          account:
            accountNumber: 270001
          charges:
          - type: MONTHLY_RECURRING
            price: 495
          currency: USD
          timeService:
            type: NTP
            package:
              code: NTP_STANDARD
            connection:
              aSide:
                accessPoint:
                  location:
                    metroCode: CH
                    ibx: CH3
    VirtualPortProduct:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_PORT_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '270001'
          - property: /port/location/ibx
            operator: '='
            values:
            - DA1
          - property: /port/type
            operator: '='
            values:
            - XF_PORT
          - property: /port/bandwidth
            operator: '='
            values:
            - '1000'
          - property: /port/settings/buyout
            operator: '='
            values:
            - 'false'
          - property: /port/serviceType
            operator: '='
            values:
            - EPL
          - property: /port/connectivitySource/type
            operator: '='
            values:
            - COLO
          - property: /port/lag/enabled
            operator: '='
            values:
            - 'false'
    VirtualPortProductUPP:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_PORT_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '270001'
          - property: /port/location/ibx
            operator: '='
            values:
            - DA1
          - property: /port/type
            operator: '='
            values:
            - XF_PORT
          - property: /port/bandwidth
            operator: '='
            values:
            - '1000'
          - property: /port/package/code
            operator: '='
            values:
            - UNLIMITED_PLUS
          - property: /port/serviceType
            operator: '='
            values:
            - EPL
          - property: /port/connectivitySource/type
            operator: '='
            values:
            - COLO
          - property: /port/lag/enabled
            operator: '='
            values:
            - 'false'
    VirtualPortUPP:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: VIRTUAL_PORT_PRODUCT
          code: ECX00001.PROD
          name: Equinix Fabric Port Product
          description: Equinix Fabric Port
          account:
            accountNumber: 200001
          charges:
          - type: MONTHLY_RECURRING
            price: 500
          - type: NON_RECURRING
            price: 100
          currency: USD
          port:
            type: XF_PORT
            location:
              ibx: DA1
            lag:
              enabled: false
            physicalPortsQuantity: 1
            bandwidth: 1000
            connectivitySource:
              type: COLO
            serviceType: EPL
            package:
              code: UNLIMITED_PLUS
    VirtualConnectionProductGwVcTypeFromGWToSP:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - IP_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - CLOUD_ROUTER
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - SV
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - SP
          - property: /connection/zSide/accessPoint/profile/uuid
            operator: '='
            values:
            - efeed227-765e-4f74-b14c-0c8a739be23e
    VirtualPortIX:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: VIRTUAL_PORT_PRODUCT
          code: IX00008.PROD
          name: Equinix Internet Exchange Port Product
          description: Internet Exchange Port
          account:
            accountNumber: 200001
          charges:
          - type: MONTHLY_RECURRING
            price: 500
          - type: NON_RECURRING
            price: 100
          currency: USD
          port:
            type: XF_PORT
            location:
              ibx: DA1
            lag:
              enabled: false
            physicalPortsQuantity: 1
            bandwidth: 1000
            connectivitySource:
              type: COLO
            serviceCode: IX
    VirtualPort:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: VIRTUAL_PORT_PRODUCT
          code: ECX00001.PROD
          name: Equinix Fabric Port Product
          description: Equinix Fabric Port
          account:
            accountNumber: 200001
          charges:
          - type: MONTHLY_RECURRING
            price: 500
          - type: NON_RECURRING
            price: 100
          currency: USD
          port:
            type: XF_PORT
            location:
              ibx: DA1
            lag:
              enabled: false
            physicalPortsQuantity: 1
            bandwidth: 1000
            connectivitySource:
              type: COLO
            serviceType: EPL
            settings:
              buyout: false
    400_prices:
      value:
      - errorCode: EQ-3038010
        errorMessage: Validation failure
        details: Invalid request body
        additionalInfo:
        - property: /connection/zSide/accessPoint/location/metroCode
          reason: /connection/zSide/accessPoint/location/metroCode has invalid format
    VirtualConnectionProductEvplVcTypeFromColoToColo:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - EVPL_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - COLO
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/aSide/accessPoint/port/settings/buyout
            operator: '='
            values:
            - 'false'
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - COLO
    PrecisionTimeNtpEnterprisePackage:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - PRECISION_TIME_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '270001'
          - property: /timeService/type
            operator: '='
            values:
            - NTP
          - property: /timeService/package/code
            operator: '='
            values:
            - NTP_ENTERPRISE
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
    FabricCloudRouterProduct:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - CLOUD_ROUTER_PRODUCT
          - property: /router/location/metroCode
            operator: '='
            values:
            - CH
          - property: /router/package/code
            operator: IN
            values:
            - LAB
            - ADVANCED
            - STANDARD
            - PREMIUM
    500_prices:
      value:
      - errorCode: EQ-3038030
        errorMessage: Internal Server Error
        details: We couldn't process you request
    MetroConnectProduct:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - METRO_CONNECT_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '200551'
          - property: /metroConnect/type
            operator: '='
            values:
            - OPTICAL_MC
          - property: /metroConnect/bandwidth
            operator: '='
            values:
            - '1000'
          - property: /metroConnect/pathType
            operator: '='
            values:
            - PROTECTED
          - property: /metroConnect/connectionDestinationType
            operator: '='
            values:
            - COLO
          - property: /metroConnect/aSide/location/ibxCode
            operator: '='
            values:
            - CH1
          - property: /metroConnect/zSide/location/ibxCode
            operator: '='
            values:
            - CH3
    VirtualConnectionProductGwVcTypeFromGWToColo:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - IP_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - CLOUD_ROUTER
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - COLO
    PrecisionTimeNtpStandardPackage:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - PRECISION_TIME_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '270001'
          - property: /timeService/type
            operator: '='
            values:
            - NTP
          - property: /timeService/package/code
            operator: '='
            values:
            - NTP_STANDARD
          - property: /connection/aSide/accessPoint/location/ibx
            operator: '='
            values:
            - CH3
    VirtualConnectionProductOfflineEvplVcTypeFromColoToSp:
      value:
        filter:
          or:
          - and:
            - property: /type
              operator: '='
              values:
              - VIRTUAL_CONNECTION_PRODUCT
            - property: /connection/type
              operator: '='
              values:
              - EVPL_VC
            - property: /connection/bandwidth
              operator: IN
              values:
              - '100'
            - property: /connection/aSide/accessPoint/type
              operator: '='
              values:
              - COLO
            - property: /connection/aSide/accessPoint/location/metroCode
              operator: '='
              values:
              - CH
            - property: /connection/aSide/accessPoint/port/settings/buyout
              operator: '='
              values:
              - 'false'
            - property: /connection/zSide/accessPoint/location/metroCode
              operator: '='
              values:
              - CH
            - property: /connection/zSide/accessPoint/type
              operator: '='
              values:
              - SP
            - property: /connection/zSide/accessPoint/profile/uuid
              operator: '='
              values:
              - efeed227-765e-4f74-b14c-0c8a739be23e
          - and:
            - property: /connection/uuid
              operator: '='
              values:
              - efeed227-765e-4f74-b14c-0c8a739be23e
    VirtualConnectionProductEvplVcTypeFromColoToColoByPortUuid:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - EVPL_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - COLO
          - property: /connection/aSide/accessPoint/port/uuid
            operator: '='
            values:
            - b840a1db-54ab-4abf-97e0-328a5c00a874
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - COLO
    IpBlock:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: IP_BLOCK_PRODUCT
          code: ECX00005.PROD
          name: Equinix Fabric IP Addressing Product
          description: Equinix Fabric IP Addressing
          charges:
          - type: MONTHLY_RECURRING
            price: 20
          currency: USD
          ipBlock:
            type: IPv4
            prefixLength: 29
            location:
              metroCode: CH
    VirtualConnectionProductEvplVcTypeFromVDToColo:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - EVPL_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - VD
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - SV
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - COLO
    VirtualConnectionProductGwVcTypeFromVDToColo:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - IP_VC
          - property: /connection/bandwidth
            operator: IN
            values:
            - '100'
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - VD
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - CH
          - property: /connection/zSide/accessPoint/location/metroCode
            operator: '='
            values:
            - SV
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - SP
          - property: /connection/zSide/accessPoint/profile/uuid
            operator: '='
            values:
            - efeed227-765e-4f74-b14c-0c8a739be23e
    FabricCloudRouter:
      value:
        pagination:
          offset: 0
          limit: 1
          total: 1
        data:
        - type: CLOUD_ROUTER_PRODUCT
          code: ECX00014.PROD
          name: Equinix Cloud Router Product
          description: Equinix Cloud Router
          account:
            accountNumber: 200001
          charges:
          - type: MONTHLY_RECURRING
            price: 5000
          currency: USD
          router:
            package:
              code: ADVANCED
            location:
              metroCode: CH
    VirtualConnectionProductEvpLanVcTypeFromColoToNetwork:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - VIRTUAL_CONNECTION_PRODUCT
          - property: /connection/type
            operator: '='
            values:
            - EVPLAN_VC
          - property: /connection/aSide/accessPoint/type
            operator: '='
            values:
            - COLO
          - property: /connection/aSide/accessPoint/location/metroCode
            operator: '='
            values:
            - DA
          - property: /connection/aSide/accessPoint/port/settings/buyout
            operator: '='
            values:
            - 'true'
          - property: /connection/zSide/accessPoint/type
            operator: '='
            values:
            - NETWORK
          - property: /connection/zSide/accessPoint/network/scope
            operator: '='
            values:
            - REGIONAL
          - property: /connection/bandwidth
            operator: IN
            values:
            - '10'
    PrecisionTimePtpStandardPackage:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - PRECISION_TIME_PRODUCT
          - property: /account/accountNumber
            operator: '='
            values:
            - '270001'
          - property: /timeService/type
            operator: '='
            values:
            - PTP
          - property: /timeService/package/code
            operator: '='
            values:
            - PTP_STANDARD
          - property: /connection/aSide/accessPoint/location/ibx
            operator: '='
            values:
            - CH3
    IpBlockProduct:
      value:
        filter:
          and:
          - property: /type
            operator: '='
            values:
            - IP_BLOCK_PRODUCT
          - property: /ipBlock/type
            operator: '='
            values:
            - IPv4
          - property: /ipBlock/prefixLength
            operator: '='
            values:
            - '29'
          - property: /ipBlock/location/metroCode
            operator: IN
            values:
            - SV
            - WA
  schemas:
    VirtualPortServiceCode:
      type: string
      description: Port service code.
    VirtualConnectionPriceZSide_accessPoint_bridge_package:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/VirtualConnectionBridgePackageCode'
    PriceLocation:
      type: object
      properties:
        metroCode:
          type: string
        ibx:
          type: string
    VirtualConnectionPriceASide_accessPoint:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/VirtualConnectionPriceAccessPointType'
        location:
          $ref: '#/components/schemas/PriceLocation'
        port:
          $ref: '#/components/schemas/VirtualConnectionPriceASide_accessPoint_port'
    VirtualPortRedundancy:
      type: object
      properties:
        enabled:
          type: boolean
          description: Parameter showing whether redundancy is mandatory. The default is false.
          default: false
      description: Specifications for redundant connections, which improve service continuity by routing traffic to secondary ports when primary ports are unavailable. <br> Redundancy increases resilience and boosts site reliability scores.
    PriceSearchResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Price'
        pagination:
          $ref: '#/components/schemas/Pagination'
    VirtualPortConfiguration:
      type: object
      properties:
        buyout:
          type: boolean
          description: Buyout (true) or standard (false) configuration of the port at this access point. <br> Buyout ports offer free, unlimited connections. Standard ports do not. The default is false.
          default: false
      description: Port configuration.
    VirtualPortPrice:
      type: object
      properties:
        uuid:
          type: string
          description: Unique identifier assigned to the virtual port. Either the uuid or the remaining attributes must be supplied.
          format: uuid
        type:
          $ref: '#/components/schemas/VirtualPortType'
        location:
          $ref: '#/components/schemas/VirtualPortLocation'
        lag:
          $ref: '#/components/schemas/LinkAggregationGroup'
        physicalPortsQuantity:
          type: integer
          description: Number of physical ports requested. The defaults is 1.
          default: 1
        bandwidth:
          type: integer
          description: Aggregated data transfer capacity,  expressed as follows <br> -> Mbps, megabits (1 million bits) per second <br> -> Gbps, gigabits (1 billion bits) per second <br> Bandwidth must be divisible by physicalPortsQuantity.
        redundancy:
          $ref: '#/components/schemas/VirtualPortRedundancy'
        connectivitySource:
          $ref: '#/components/schemas/ConnectivitySource'
        serviceType:
          $ref: '#/components/schemas/VirtualPortServiceType'
        settings:
          $ref: '#/components/schemas/VirtualPortConfiguration'
        package:
          $ref: '#/components/schemas/VirtualPortPackage'
        serviceCode:
          $ref: '#/components/schemas/VirtualPortServiceCode'
      description: Preferences and settings for a virtual port connected to an internet service provider (ISP) or other Equinix platform entity.
    VirtualConnectionBridgePackageCode:
      type: string
      description: Virtual Connection bridge package code
      enum:
      - REGIONAL
      - GLOBAL
    VirtualConnectionPrice:
      type: object
      properties:
        uuid:
          type: string
          description: Either uuid or rest of attributes are required
          format: uuid
        type:
          $ref: '#/components/schemas/VirtualConnectionPriceConnectionType'
        bandwidth:
          minimum: 0
          type: integer
        aSide:
          $ref: '#/components/schemas/VirtualConnectionPriceASide'
        zSide:
          $ref: '#/components/schemas/VirtualConnectionPriceZSide'
      description: Virtual Connection Product configuration
    VirtualPortType:
      type: string
      description: Port type.
      enum:
      - XF_PORT
    VirtualPortServiceType:
      type: string
      description: Port service type. The default is managed-service provider (MSP).
      default: MSP
      enum:
      - MSP
      - EPL
    ConnectivitySourceType:
      type: string
      description: Type of connectivity. COLO, colocation; BMMR, building meet-me room. The default is COLO. <br> A building meet-me room (BMMR) is a room within the same building where an Equinix IBX customer can connect with a non-Equinix IBX customer.
      default: COLO
      enum:
      - COLO
      - BMMR
      - REMOTE
    Price:
      type: object
      properties:
        href:
          type: string
          description: An absolute URL that returns specified pricing data
          format: url
        type:
          $ref: '#/components/schemas/ProductType'
        code:
          type: string
          description: Equinix-assigned product code
        name:
          type: string
          description: Full product name
        description:
          type: string
          description: Product description
        account:
          $ref: '#/components/schemas/SimplifiedAccount'
        charges:
          type: array
          items:
            $ref: '#/components/schemas/PriceCharge'
        currency:
          type: string
          description: Product offering price currency
        termLength:
          type: integer
          description: In months. No value or value of 1 means on-demand
          enum:
          - 1
          - 12
          - 24
          - 36
        catgory:
          $ref: '#/components/schemas/PriceCategory'
        connection:
          $ref: '#/components/schemas/VirtualConnectionPrice'
        ipBlock:
          $ref: '#/components/schemas/IpBlockPrice'
        router:
          $ref: '#/components/schemas/FabricCloudRouterPrice'
        port:
          $ref: '#/components/schemas/VirtualPortPrice'
        timeService:
          $ref: '#/components/schemas/TimeServicePrice'
    FabricCloudRouterCode:
      type: string
      description: Cloud Router code
      enum:
      - LAB
      - BASIC
      - STANDARD
      - ADVANCED
      - PREMIUM
    TimeServicePriceConnectionASide:
      type: object
      properties:
        accessPoint:
          $ref: '#/components/schemas/TimeServicePriceConnectionAccessPoint'
      description: Time Service Price Connection ASide configuration
    TimeServicePriceConnectionAccessPoint:
      type: object
      properties:
        location:
          $ref: '#/components/schemas/PriceLocation'
      description: Time Service Price Connection Access Point configuration
    LinkAggregationGroup:
      type: object
      properties:
        enabled:
          type: boolean
          description: Parameter showing whether LAG configuration is mandatory. The default is false.
          default: false
      description: Link aggregation group (LAG) preferences and settings.
    IpBlockType:
      type: string
      description: IP Block type
      enum:
      - IPv4
      - IPv6
    precisionTimePackageRequest:
      title: precisionTimePackageRequest
      required:
      - code
      type: object
      properties:
        code:
          type: string
          description: Precision Time Service Level
          enum:
          - NTP_STANDARD
          - NTP_ENTERPRISE
          - PTP_STANDARD
          - PTP_ENTERPRISE
      description: Precision Time Service Level Request
      example:
        code: NTP_STANDARD
    ConnectivitySource:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ConnectivitySourceType'
      description: Physical or virtual port that houses the connection.
    VirtualConnectionPriceZSide:
      type: object
      properties:
        accessPoint:
          $ref: '#/components/schemas/VirtualConnectionPriceZSide_accessPoint'
    PriceCharge:
      type: object
      properties:
        type:
          type: string
          description: Price charge type
          enum:
          - MONTHLY_RECURRING
          - NON_RECURRING
        price:
          minimum: 0
          type: number
          description: Offering price
          format: double
      description: Price  Charge
    VirtualPortLocation:
      type: object
      properties:
        ibx:
          type: string
          description: Code assigned to the Equinix International Business Exchange (IBX) data center from which the port is ordered. <br> The port might be in a different location.
      description: Geographic data for the port.
    SearchExpressions:
      type: array
      items:
        $ref: '#/components/schemas/SearchExpression'
    PriceCategory:
      type: string
      description: Price category
      enum:
      - COUNTRY
      - CUSTOMER
    FabricCloudRouterPackages:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/FabricCloudRouterCode'
      description: Cloud Router  package
    TimeServicePrice:
      type: object
      properties:
        type:
          type: string
          description: Precision Time Service Type refers to the corresponding Protocol.
          enum:
          - NTP
          - PTP
        package:
          $ref: '#/components/schemas/precisionTimePackageRequest'
        connection:
          $ref: '#/components/schemas/TimeServicePriceConnection'
      description: Time Service Product configuration
    VirtualConnectionPriceZSide_accessPoint_profile:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
    VirtualConnectionPriceZSide_accessPoint:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/VirtualConnectionPriceAccessPointType'
        location:
          $ref: '#/components/schemas/PriceLocation'
        port:
          $ref: '#/components/schemas/VirtualConnectionPriceASide_accessPoint_port'
        profile:
          $ref: '#/components/schemas/VirtualConnectionPriceZSide_accessPoint_profile'
        bridge:
          $ref: '#/components/schemas/VirtualConnectionPriceZSide_accessPoint_bridge'
    PriceError:
      required:
      - errorCode
      - errorMessage
      type: object
      properties:
        errorCode:
          type: string
          enum:
          - EQ-3038010
          - EQ-3038022
          - EQ-3038030
        errorMessage:
          type: string
          enum:
          - Validation failure
          - Invalid value
          - Internal Server Error
        correlationId:
          type: string
        details:
          type: string
        help:
          type: string
        additionalInfo:
          type: array
          items:
            $ref: '#/components/schemas/PriceError_additionalInfo'
      description: Error with details
      discriminator:
        propertyName: errorCode
    VirtualConnectionPriceConnectionType:
      type: string
      description: Virtual Connection type
      enum:
      - EVPL_VC
      - EPL_VC
      - EC_VC
      - IP_VC
      - VD_CHAIN_VC
      - ACCESS_EPL_VC
      - EVPLAN_VC
      - EPLAN_VC
      - IPWAN_VC
      - EVPTREE_VC
      - EPTREE_VC
      - IA_VC
    Pagination:
      required:
      - limit
      - total
      type: object
      properties:
        offset:
          minimum: 0
          type: integer
          description: Index of the first item returned in the response. The default is 0.
          default: 0
        limit:
          minimum: 0
          type: integer
          description: Maximum number of search results returned per page. Number must be between 1 and 100, and the default is 20.
          default: 20
        total:
          minimum: 0
          type: integer
          description: Total number of elements returned.
        next:
          type: string
          description: URL relative to the next item in the response.
        previous:
          type: string
          description: URL relative to the previous item in the response.
      description: Pagination response information
    FabricCloudRouterPrice:
      type: object
      properties:
        uuid:
          type: string
          description: Unique identifier assigned to the Cloud Router
          format: uuid
        location:
          $ref: '#/components/schemas/PriceLocation'
        package:
          $ref: '#/components/schemas/FabricCloudRouterPackages'
      description: Cloud Router  Product configuration
    VirtualPortPackage:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/VirtualPortPackageCode'
      description: Virtual Port Package
    FilterBody:
      type: object
      properties:
        filter:
          $ref: '#/components/schemas/SearchExpression'
      description: Search requests containing criteria
    IpBlockPrice:
      type: object
      properties:
        uuid:
          type: string
          description: Either uuid or rest of attributes are required
          format: uuid
        type:
          $ref: '#/components/schemas/IpBlockType'
        prefixLength:
          type: integer
        location:
          $ref: '#/components/schemas/PriceLocation'
      description: IP Block Product configuration
    VirtualConnectionPriceZSide_accessPoint_bridge:
      type: object
      properties:
        package:
          $ref: '#/components/schemas/VirtualConnectionPriceZSide_accessPoint_bridge_package'
    PriceErrorList:
      type: array
      items:
        $ref: '#/components/schemas/PriceError'
    VirtualConnectionPriceASide_accessPoint_port_settings:
      type: object
      properties:
        buyout:
          type: boolean
          default: false
    VirtualConnectionPriceASide_accessPoint_port:
      type: object
      properties:
        settings:
          $ref: '#/components/schemas/VirtualConnectionPriceASide_accessPoint_port_settings'
    PriceError_additionalInfo:
      type: object
      properties:
        property:
          type: string
        reason:
          type: string
    VirtualPortPackageCode:
      type: string
      description: Virtual port package code
      example: STANDARD, UNLIMITED or UNLIMITED_PLUS
    ProductType:
      type: string
      description: Product type
      enum:
      - VIRTUAL_CONNECTION_PRODUCT
      - IP_BLOCK_PRODUCT
      - VIRTUAL_PORT_PRODUCT
      - CLOUD_ROUTER_PRODUCT
      - PRECISION_TIME_PRODUCT
      - METRO_CONNECT_PRODUCT
    SearchExpression:
      type: object
      properties:
        and:
          $ref: '#/components/schemas/SearchExpressions'
        or:
          $ref: '#/components/schemas/SearchExpressions'
        property:
          type: string
        operator:
          type: string
          enum:
          - '='
          - '!='
          - '>'
          - '>='
          - <
          - <=
          - BETWEEN
          - NOT BETWEEN
          - LIKE
          - NOT LIKE
          - IN
          - NOT IN
          - IS NOT NULL
          - IS NULL
        values:
          type: array
          items:
            type: string
    TimeServicePriceConnection:
      type: object
      properties:
        aSide:
          $ref: '#/components/schemas/TimeServicePriceConnectionASide'
      description: Time Service Price Connection configuration
    VirtualConnectionPriceAccessPointType:
      type: string
      description: Virtual Connection access point type
      enum:
      - VD
      - SP
      - COLO
      - CLOUD_ROUTER
      - CHAINGROUP
      - NETWORK
      - METAL_NETWORK
    SimplifiedAccount:
      type: object
      properties:
        accountNumber:
          type: integer
          description: Account number
          format: int64
        accountName:
          type: string
          description: Account name
        orgId:
          type: integer
          description: Customer organization identifier
          format: int64
        organizationName:
          type: string
          description: Customer organization name
        globalOrgId:
          type: string
          description: Global organization identifier
        globalOrganizationName:
          type: string
          description: Global organization name
        ucmId:
          type: string
          description: Account ucmId
        globalCustId:
          type: string
          description: Account name
        resellerAccountNumber:
          type: integer
          description: Reseller account number
          format: int64
        resellerAccountName:
          type: string
          description: Reseller account name
        resellerUcmId:
          type: string
          description: Reseller account ucmId
        resellerOrgId:
          type: integer
          description: Reseller customer organization identifier
          format: int64
    VirtualConnectionPriceASide:
      type: object
      properties:
        accessPoint:
          $ref: '#/components/schemas/VirtualConnectionPriceASide_accessPoint'
x-eqx-api-linter-skip-rules:
- 3
- 38
