openapi: 3.2.0
info:
  title: Equinix Fabric API v4 Port Packages API
  description: 'Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br> </br> <b>Integrations (SDKs, Tools) links:</b> </br> <a href="https://github.com/equinix/equinix-sdk-java">Fabric Java SDK</a> </br> <a href="https://github.com/equinix/equinix-sdk-go">Fabric Go SDK</a> </br> <a href="https://github.com/equinix/equinix-sdk-python">Fabric Python SDK</a> </br> <a href="https://registry.terraform.io/providers/equinix/equinix/latest/docs">Equinix Terraform Provider</a> </br> <a href="https://registry.terraform.io/modules/equinix/fabric/equinix/latest">Fabric Terraform Modules</a> </br> <a href="https://www.pulumi.com/registry/packages/equinix/">Equinix Pulumi Provider</a> </br>'
  termsOfService: https://www.equinix.com/about/legal/terms
  contact:
    name: Equinix API Support
    url: https://docs.equinix.com/api-support.htm
  license:
    name: Equinix Inc
    url: https://developer.equinix.com/agreement
  version: '4.28'
servers:
- url: https://api.equinix.com
  description: Equinix Inc
security:
- BearerAuth: []
tags:
- name: Port Packages
  description: Port Packages <font color="red"> <sup color='red'>Beta</sup></font>
paths:
  /fabric/v4/portPackages:
    get:
      tags:
      - Port Packages
      summary: Get All Port Packages
      description: Get All Port Packages returns details of all available port packages for the specified user credentials.
      operationId: getPortPackages
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllPortPackagesResponse'
              examples:
                portPackagesExample:
                  $ref: '#/components/examples/port-packages'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                example:
                  $ref: '#/components/examples/401'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                example:
                  $ref: '#/components/examples/403'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                example:
                  $ref: '#/components/examples/415'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
              examples:
                portPackagesInternalErrorExample:
                  $ref: '#/components/examples/port-packages-500'
components:
  schemas:
    Error:
      required:
      - errorCode
      - errorMessage
      type: object
      properties:
        errorCode:
          pattern: ^EQ-\d{7}$
          type: string
        errorMessage:
          type: string
        correlationId:
          type: string
        details:
          type: string
        help:
          type: string
        additionalInfo:
          type: array
          items:
            $ref: '#/components/schemas/PriceError_additionalInfo'
      description: Error Response with details
    PortPackage:
      required:
      - code
      - type
      type: object
      properties:
        href:
          type: string
          description: Port Package URI
          readOnly: true
        type:
          type: string
          description: Port Package Type
          enum:
          - PORT_PACKAGE
        code:
          type: string
          description: Port Package code
        vcBandwidthMax:
          type: integer
          description: Maximum virtual connection bandwidth in Mbps
        vcRemoteSupported:
          type: boolean
          description: Indicates if remote virtual connections are supported
        supportedServiceTypes:
          type: array
          description: List of supported service types
          items:
            type: string
            description: Port Package Service Type
            enum:
            - MSP
        supportedSourceTypes:
          type: array
          description: List of supported source types
          items:
            $ref: '#/components/schemas/PortPackageSourceType'
        supportedMetros:
          type: array
          description: List of supported metros
          items:
            type: string
      description: Port Package details
    ErrorList:
      type: array
      description: List of Error Message
      items:
        $ref: '#/components/schemas/Error'
    PortPackageSourceType:
      type: string
      description: Port Package Source Type
      enum:
      - COLO
      - REMOTE
      - BMMR
    AllPortPackagesResponse:
      required:
      - data
      type: object
      properties:
        data:
          type: array
          description: List of Port Packages
          items:
            $ref: '#/components/schemas/PortPackage'
      description: Port Packages response
    PriceError_additionalInfo:
      type: object
      properties:
        property:
          type: string
        reason:
          type: string
  examples:
    '415':
      value:
      - errorCode: EQ-3040016
        errorMessage: Unsupported media type, please check the request's Content-Type or Content-Encoding
        correlationId: cebc3d33-9037-4a2b-a7af-0ad65602cdec
        additionalInfo:
        - property: contentType
          reason: The payload format is in an unsupported format
    '403':
      value:
      - errorCode: EQ-3045003
        errorMessage: Operation not allowed
        correlationId: c82ff3bc-de07-47e5-b3ec-53a009d01515
        details: Operation not allowed for current user
    '401':
      value:
      - errorCode: EQ-3000039
        errorMessage: User not found in request or invalid.
        correlationId: c82ff3bc-de07-47e5-b3ec-53a009d01515
    port-packages:
      value:
        data:
        - href: /fabric/v4/portPackages/XF_UNLIMITED_PLUS
          type: PORT_PACKAGE
          code: XF_UNLIMITED_PLUS
          vcBandwidthMax: 100000
          vcRemoteSupported: true
          supportedServiceTypes:
          - MSP
          supportedSourceTypes:
          - COLO
          supportedMetros:
          - SV
          - DA
        - href: /fabric/v4/portPackages/XF_UNLIMITED
          type: PORT_PACKAGE
          code: XF_UNLIMITED
          vcBandwidthMax: 100000
          vcRemoteSupported: false
          supportedServiceTypes:
          - MSP
          supportedSourceTypes:
          - REMOTE
          - COLO
        - href: /fabric/v4/portPackages/XF_STANDARD
          type: PORT_PACKAGE
          code: XF_STANDARD
          vcBandwidthMax: 100000
          vcRemoteSupported: false
          supportedServiceTypes:
          - MSP
          supportedSourceTypes:
          - BMMR
          - REMOTE
          - COLO
    port-packages-500:
      value:
      - errorCode: EQ-3143001
        errorMessage: Internal Error
        details: Internal system error
        correlationId: 80066c00-0f20-11f0-8367-d5075ee362a7
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
externalDocs:
  description: Find more information on Equinix Docs Portal
  url: https://docs.equinix.com/fabric/
